LucasTesnier/ZAAAAAAAAAAAAppy

- src/zappy_gui/Core/SFML/CMakeLists.txt
- src/zappy_gui/Core/SFML/WrapperSFML/CMakeLists.txt
- src/zappy_gui/Core/SFML/WrapperSFML/Event.hpp
This pull request is link to the issue #58.
It creates the Event class to handle SFML event easier.
> GUI/event handling/58

- src/zappy_gui/Core/SFML/SFML.cpp
- src/zappy_gui/Core/SFML/SFML.hpp
- src/zappy_gui/Core/SFML/WrapperSFML/CMakeLists.txt
It adds the SFML part. It contains the main loop, the event handling, and a little fix in a CMakeLists.txt of the event part.
Link to the issue: #68.
> GUI - SFML

- src/zappy_server_src/core/argument_handling.c
- src/zappy_server_src/core/include/my_zappy_server.h
- src/zappy_server_src/core/my_zappy_server.c
- src/zappy_server_src/core/server_data.c
- src/zappy_server_src/net_utils/include/net_utils.h
- src/zappy_server_src/net_utils/tcp_server.c
Add a custom value for the listen queue.
Change the max clientNb value.
> 8/Server - Listen

- .gitignore
- src/zappy_ai_src/CMakeLists.txt
- src/zappy_ai_src/network/CMakeLists.txt
- src/zappy_ai_src/network/api/CMakeLists.txt
- src/zappy_ai_src/network/api/authentification.c
- src/zappy_ai_src/network/api/include/api.h
- src/zappy_ai_src/network/api/include/intern_data.h
- src/zappy_ai_src/network/entrypoint.c
- src/zappy_ai_src/network/net_utils/CMakeLists.txt
- src/zappy_ai_src/network/net_utils/client_utils.c
- src/zappy_ai_src/network/net_utils/fetch_message.c
- src/zappy_ai_src/network/net_utils/include/client_utils.h
- src/zappy_ai_src/network/net_utils/include/internals.h
- src/zappy_ai_src/network/net_utils/manage_fd_sets.c
- src/zappy_ai_src/network/net_utils/send_message.c
- src/zappy_ai_src/network/net_utils/update_client.c
Implement the architecture of the network API.
Add login and logout to the network server process.
> 14/ClientAI - Network API

- src/zappy_server_src/net_utils/fd_sets_manage/server_read_client.c
Refactoring the request queue.
Pop the first element and not the last.
> 11/Server - Request Queue

- src/zappy_gui_src/Core/SFML/Map/CMakeLists.txt
- src/zappy_gui_src/Core/SFML/Map/Tile.cpp
- src/zappy_gui_src/Core/SFML/Map/Tile.hpp
This pull request adds the class tile to be use by the class map, and represent a tile.
> GUI - Implement Tile class

- .gitignore
- src/zappy_ai_src/CMakeLists.txt
- src/zappy_ai_src/ai_DLLib_wrapper.py
- src/zappy_ai_src/network/CMakeLists.txt
- src/zappy_ai_src/zappy_ai
With the parameter, search in the /etc/hosts file to find the corresponding Ip
Raise a RunTimeError if the Ip isn't found
> ClientAI - Find the Ip corresponding to the hostname

- src/zappy_ai_src/ai_DLLib_wrapper.py
- src/zappy_ai_src/ai_core.py
- src/zappy_ai_src/ai_function_wrapper.py
- src/zappy_ai_src/zappy_ai
Add a Core Client object
This will be the main object for the client
The connectToServer() method tries to connect the client to the server with the given parameter
> ClientAI - CoreClient

- src/zappy_server_src/core/commands/auth_command.c
Thix PR fixes a bad merge before the previous PR on the same branch was made, srry for the inconvenience
> [*] Fix auth_command.c bad merge

- src/zappy_ai_src/ai_function_wrapper.py
- src/zappy_ai_src/ai_handle_response.py
Add a wrapped function for the network state
Add another method to get a tile with only one parameter from the map
> ClientAI - Minor Adds

- src/zappy_server_src/core/command_hold.c
- src/zappy_server_src/core/include/command_hold.h
- src/zappy_server_src/core/include/server.h
- src/zappy_server_src/core/server_data.c
- src/zappy_server_src/core/server_run.c
Implement the scheduler ending process
> 103/Server Scheduler Ending

- src/zappy_gui_src/Core/SFML/Interface/Interface.cpp
- src/zappy_gui_src/Core/SFML/Interface/Interface.hpp
- src/zappy_gui_src/Core/SFML/SFML.cpp
- src/zappy_gui_src/Core/SFML/SFML.hpp
This is a basic pull request to implement the interface class in the project. It will be completed by some class which will be added to the interface class.
> GUI - Menu - Interface

- src/zappy_gui_src/Core/Core.cpp
- src/zappy_gui_src/Core/SFML/Map/Map.cpp
- src/zappy_gui_src/Core/SFML/Map/Map.hpp
- src/zappy_gui_src/Core/SFML/Map/Tile.cpp
- src/zappy_gui_src/Core/SFML/Map/Tile.hpp
- src/zappy_gui_src/Core/SFML/SFML.cpp
This pull request implements some optimization on the map displayed.
> GUI - Map - Optimisation

- src/zappy_ai_src/network/api/CMakeLists.txt
- src/zappy_ai_src/network/api/ask/forward.c
- src/zappy_ai_src/network/api/ask/inventory.c
- src/zappy_ai_src/network/api/ask/join.c
- src/zappy_ai_src/network/api/ask/send_request.c
- src/zappy_ai_src/network/api/authentification.c
- src/zappy_ai_src/network/api/get/forward.c
- src/zappy_ai_src/network/api/get/inventory.c
- src/zappy_ai_src/network/api/get/join.c
- src/zappy_ai_src/network/api/get/retcode.c
- src/zappy_ai_src/network/api/include/api.h
- src/zappy_ai_src/network/api/include/intern_data.h
- src/zappy_ai_src/network/entrypoint.c
- src/zappy_server_src/core/command_hold.c
- src/zappy_server_src/core/commands/CMakeLists.txt
- src/zappy_server_src/core/commands/forward_command.c
- src/zappy_server_src/core/include/command_hold.h
- src/zappy_server_src/core/include/rcodes.h
- src/zappy_server_src/core/scheduler.c
- src/zappy_server_src/core/server_run.c
Implement Inventory Join and Forward action.
> 89/Server - API Response

- src/zappy_server_src/core/commands/forward_command.c
> [+] Add forward command support

- src/zappy_ai_src/network/api/CMakeLists.txt
- src/zappy_ai_src/network/api/get/retcode.c
- src/zappy_ai_src/network/api/get/unexpected.c
- src/zappy_ai_src/network/api/include/api.h
- src/zappy_ai_src/network/entrypoint.c
- src/zappy_server_src/core/argument_handling.c
- src/zappy_server_src/core/command_hold.c
- src/zappy_server_src/core/commands/CMakeLists.txt
- src/zappy_server_src/core/commands/connectnbr_command.c
- src/zappy_server_src/core/commands/eject_command.c
- src/zappy_server_src/core/commands/forward_command.c
- src/zappy_server_src/core/commands/place_command.c
- src/zappy_server_src/core/commands/take_command.c
- src/zappy_server_src/core/commands/turn_command.c
- src/zappy_server_src/core/commands/unexpected_send.c
- src/zappy_server_src/core/entity/player.c
- src/zappy_server_src/core/include/command_hold.h
- src/zappy_server_src/core/include/rcodes.h
- src/zappy_server_src/core/map.c
Implement the unexpected response traitment for AI and server.
Add the applicatif part for : turn, connectnbr, eject, take, place function.
Set the -f default value to 100.
> 89/Server - API AI

- src/zappy_gui_src/Core/CMakeLists.txt
- src/zappy_gui_src/Core/Core.cpp
- src/zappy_gui_src/Core/Core.hpp
- src/zappy_gui_src/Core/Network/Unpack.cpp
- src/zappy_gui_src/Core/Network/Unpack.hpp
- src/zappy_gui_src/Core/SFML/SFML.cpp
- src/zappy_gui_src/Core/SFML/SFML.hpp
- src/zappy_server_src/core/commands/start_information.c
Link the Gui and the server.
Communication in start processus and map size updated.
> 129/GUI - Communication

- src/zappy_ai_src/ai_core.py
- src/zappy_ai_src/ai_strategy_management.py
- src/zappy_server_src/core/commands/look_command.c
- src/zappy_server_src/core/server_run.c
This PR fixes many functionals bug, adding some debugs that are very useful after
We're still missing the capability to evolve
> ClientAI - Server Link

- src/zappy_server_src/core/CMakeLists.txt
- src/zappy_server_src/core/commands/eject_command.c
- src/zappy_server_src/core/commands/forward_command.c
- src/zappy_server_src/core/entity/tile.c
- src/zappy_server_src/core/include/map.h
- src/zappy_server_src/core/map_utils.c
- Fix a wrong calculation in `forward_command` and `eject_command`
- Add some map debug info
> `fix_get_tile` calculation

- src/zappy_ai_src/network/api/get/retcode.c
- src/zappy_server_src/core/commands/fork_command.c
- src/zappy_server_src/core/commands/inventory_command.c
- src/zappy_server_src/core/commands/join_command.c
- src/zappy_server_src/core/entity/entity_wrapper_create.c
- src/zappy_server_src/core/include/command_hold.h
- src/zappy_server_src/core/include/entity/entity.h
- src/zappy_server_src/core/include/rcodes.h
- src/zappy_server_src/core/server_run.c
- src/zappy_server_src/core/team.c
Implement the Fork command in the applicatif side.
Fix some missing free.
> 89/Server - Fork Applicatif

- src/zappy_ai_src/ai_core.py
- src/zappy_ai_src/ai_function_wrapper.py
The AI was missing an error handling while connecting to the server, which led to undefined behavior
> ClientAI - Error Handling on server connection

- src/zappy_ai_src/ai_core.py
- src/zappy_ai_src/ai_function_wrapper.py
Reverts LucasTesnier/ZAAAAAAAAAAAAppy#141
> Revert "ClientAI - Error Handling on server connection"

- src/zappy_ai_src/network/api/ask/broadcast.c
- src/zappy_ai_src/network/api/ask/connectnbr.c
- src/zappy_ai_src/network/api/ask/eject.c
- src/zappy_ai_src/network/api/ask/fork.c
- src/zappy_ai_src/network/api/ask/forward.c
- src/zappy_ai_src/network/api/ask/incantation.c
- src/zappy_ai_src/network/api/ask/inventory.c
- src/zappy_ai_src/network/api/ask/join.c
- src/zappy_ai_src/network/api/ask/look.c
- src/zappy_ai_src/network/api/ask/place.c
- src/zappy_ai_src/network/api/ask/take.c
- src/zappy_ai_src/network/api/ask/turn.c
Ask the network state function before every ask function.
> 133/APIAI - Network state

- src/zappy_server_src/core/commands/auth_command.c
- src/zappy_server_src/core/commands/entity_info.c
- src/zappy_server_src/core/commands/map_info.c
- src/zappy_server_src/core/commands/start_information.c
- src/zappy_server_src/core/commands/unexpected_send.c
- src/zappy_server_src/core/server_data.c
- src/zappy_server_src/net_utils/fd_sets_manage/server_close_client.c
Handle some bug with logout of client.
GUI can now logout and login in one server instance.
Correction of the memory lost when client close on his side.
Add some verification to unexpected event send.
> 134/Server - Logout

- src/zappy_ai_src/ai_function_wrapper.py
Corresponding to the RFC, the client now flushes after ask methods
> ClientIA - Flush on all ask functions

- src/zappy_server_src/core/player_life.c
Add drop of ressource when player dead.
> 142/Server - Drop

- src/zappy_ai_src/network/entrypoint.c
- src/zappy_server_src/core/commands/join_command.c
- src/zappy_server_src/net_utils/fd_sets_manage/server_read_client.c
- src/zappy_server_src/net_utils/fd_sets_manage/server_write_client.c
- src/zappy_server_src/net_utils/include/net_utils.h
- src/zappy_server_src/net_utils/peer.c
Fix the network command overflow.
Fix the player spawn in non square map.
> 142/HotFix - NetUtils Parse

- src/zappy_ai_src/ai_queue_wrapper.py
- src/zappy_ai_src/ai_strategy_management.py
The AI queue now returns only one object when pop
The response handling is done in the AI class to modify the corresponding variables
> Refactor of handling response in AI queue

- src/zappy_server_src/core/commands/fork_utils.c
- src/zappy_server_src/core/commands/incantation_command.c
- src/zappy_server_src/core/entity/player.c
- src/zappy_server_src/core/include/incantation.h
- src/zappy_server_src/core/include/remove_inventory.h
Fix the incantation ressource removing. No it's randomly between all the users.
Change the duration of eggs scheduling.
> 142/HotFix - Incantation

- src/zappy_server_src/core/commands/incantation_command.c
- src/zappy_server_src/core/commands/look_command.c
- src/zappy_server_src/core/commands/look_utils.c
- src/zappy_server_src/core/include/command_hold.h
- src/zappy_server_src/core/include/server.h
- src/zappy_server_src/core/server_data.c
Fix the fact that an incantation are not stopped when the player has been ejected during doing it.
> 142/HotFix - Incantation Ejected

- src/zappy_ai_src/ai_broadcast_to_object.py
- src/zappy_ai_src/ai_strategy_management.py
When the client receives an unexpected response, it can be a message from a broadcast.
Corresponding to #43, parse and create BroadcastInfo object to have clear information
> ClientAI - Parse Broadcast text 

- src/zappy_ai_src/ai_strategy_management.py
The wait for action method was quitting if we receive an unexpected response or it should leave only when this is the right answer
Create three types:  UNEXPECTED, EXPECTED, and STOPPED
> ClientAI - Hotfix for the __waitForAction method

- Doxyfile
- Fix target source folder
- Update project synopsys
- Fix CI/CD doc deployment
> [*] Fix doxyfile

- src/zappy_ai_src/network/net_utils/fetch_message.c
- src/zappy_server_src/core/commands/look_command.c
Fix the AI api overflow when an input is too much bigger.
> 142/HotFix - AI Api Overflow

- src/zappy_gui_src/Core/SFML/Interface/Interface.cpp
- src/zappy_gui_src/Core/SFML/Interface/Inventory/Inventory.cpp
- src/zappy_gui_src/Core/SFML/Interface/Inventory/Inventory.hpp
- src/zappy_gui_src/Core/SFML/Interface/ServerCommunication/ServerCommunication.cpp
- src/zappy_gui_src/Core/SFML/Interface/ServerCommunication/ServerCommunication.hpp
- src/zappy_gui_src/Core/SFML/SFML.cpp
- src/zappy_gui_src/Core/SFML/WrapperSFML/Event.hpp
Implement scroll in the bottom menu for players and eggs.
> GUI/menus/add scroll/172

- src/zappy_gui_src/Core/Core.cpp
- src/zappy_gui_src/Core/Entity/Entity.hpp
- src/zappy_gui_src/Core/Network/Unpack.cpp
- src/zappy_gui_src/Core/Network/Unpack.hpp
- src/zappy_gui_src/Core/SFML/Map/Map.hpp
- src/zappy_gui_src/Core/SFML/SFML.hpp
parsing the status response from the server and sending it to the map
> GUI/Core/Parse Status/185

- src/zappy_server_src/core/commands/join_command.c
- src/zappy_server_src/core/commands/map_info.c
- src/zappy_server_src/core/server_data.c
- Fix coding style
-  Fix bad cast
> 142/hot fix/optimisation

- src/zappy_server_src/core/commands/eject_command.c
- src/zappy_server_src/core/commands/forward_command.c
Refacto the Forward and eject moving command.
> 142/HotFix - Forward Eject

- src/zappy_server_src/core/commands/look_utils.c
- src/zappy_server_src/core/include/broadcast.h
Refacto the positional case translation for Look and broadcast.
> 142/HotFix - Look Broadcast

- src/zappy_server_src/core/entity/CMakeLists.txt
- src/zappy_server_src/core/entity/entity_diff_remove.c
- src/zappy_server_src/core/include/entity/entity.h
- src/zappy_server_src/core/player_life.c
- src/zappy_server_src/core/server_data.c
Remove dead entities from the modified entity list.
> 142/HotFix - Entity Modified List

- src/zappy_gui_src/Core/SFML/Map/Map.cpp
> fix player color
